* SnowSQL * v1.1.83
Type SQL statements or !help
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| GET_DDL('DATABASE', 'GMP_DEV')                                                                                                                                                                            |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| create or replace database GMP_DEV;                                                                                                                                                                       |
|                                                                                                                                                                                                           |
| create or replace schema PUBLIC;                                                                                                                                                                          |
|                                                                                                                                                                                                           |
| create or replace TABLE ERROR_LOG (                                                                                                                                                                       |
| 	ID NUMBER(38,0) NOT NULL autoincrement,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	COMPONENT_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_ID NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ENVIRONMENT_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_MARKET VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ERROR VARCHAR(16777216) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	FILE_IDENTIFIER VARCHAR(50),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	unique (ID)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| )COMMENT='This table will log errors for any operations'                                                                                                                                                  |
| ;                                                                                                                                                                                                         |
| create or replace TABLE ERROR_LOG_TEST (                                                                                                                                                                  |
| 	ID NUMBER(38,0) NOT NULL autoincrement,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	COMPONENT_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_ID NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ENVIRONMENT_NAME VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_MARKET VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ERROR VARCHAR(16777216) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	FILE_IDENTIFIER VARCHAR(50),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	unique (ID)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| )COMMENT='This table will log errors for any operations'                                                                                                                                                  |
| ;                                                                                                                                                                                                         |
| create or replace TABLE FILES (                                                                                                                                                                           |
| 	FILE VARCHAR(16777216)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| );                                                                                                                                                                                                        |
| create or replace TABLE FILE_AUDIT_HISTORY (                                                                                                                                                              |
| 	FILE_IDENTIFIER VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_PATH VARCHAR(2000) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_NAME VARCHAR(500) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_SIZE_BYTES NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_CREATED TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_MODIFIED TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TRAGET_FILE_PATH VARCHAR(2000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TRAGET_FILE_NAME VARCHAR(500),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TARGET_FILE_SIZE_BYTES NUMBER(38,0),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_MARKET VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_HASH VARCHAR(1000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TARGET_HASH VARCHAR(1000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	INGESTED_FLAG NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	IN_DL_FLAG NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_ID NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ENVIRONMENT VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	STATUS VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	MESSAGE VARCHAR(16777216) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	LAST_UPDATED_TS TIMESTAMP_NTZ(9) NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                                       |
| )COMMENT='This table will log File Audit for File fetch from SFTP and uploaded to Caspian S3.'                                                                                                            |
| ;                                                                                                                                                                                                         |
| create or replace TABLE FILE_AUDIT_HISTORY_2 (                                                                                                                                                            |
| 	FILE_IDENTIFIER VARCHAR(50) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_PATH VARCHAR(2000) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_NAME VARCHAR(500) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_SIZE_BYTES NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_CREATED TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_FILE_MODIFIED TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TRAGET_FILE_PATH VARCHAR(2000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TRAGET_FILE_NAME VARCHAR(500),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TARGET_FILE_SIZE_BYTES NUMBER(38,0),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_MARKET VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	SOURCE_HASH VARCHAR(1000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	TARGET_HASH VARCHAR(1000),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	INGESTED_FLAG NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	IN_DL_FLAG NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	JOB_ID NUMBER(38,0) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	ENVIRONMENT VARCHAR(255) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	STATUS VARCHAR(20) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	MESSAGE VARCHAR(16777216) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	CREATED_TS TIMESTAMP_NTZ(9) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	LAST_UPDATED_TS TIMESTAMP_NTZ(9) NOT NULL                                                                                                                                                                                                                                                                                                                                                                                                                       |
| )COMMENT='This table will log File Audit for File fetch from SFTP and uploaded to Caspian S3.'                                                                                                            |
| ;                                                                                                                                                                                                         |
| create or replace TABLE P1 (                                                                                                                                                                              |
| 	ID NUMBER(38,0),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	NAME VARCHAR(20)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| );                                                                                                                                                                                                        |
| create or replace TABLE TEMP (                                                                                                                                                                            |
| 	ID VARCHAR(16777216),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	NAME VARCHAR(16777216)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| );                                                                                                                                                                                                        |
| create or replace TABLE UPDATE_TEST (                                                                                                                                                                     |
| 	C1 NUMBER(38,0),                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	C2 VARCHAR(16777216)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| );                                                                                                                                                                                                        |
| create or replace TABLE UPDATE_TEST_INDEX (                                                                                                                                                               |
| 	C1 NUMBER(38,0) NOT NULL autoincrement,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	C2 VARCHAR(200) NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                       |
| 	unique (C1)                                                                                                                                                                                                                                                                                                                                                                                                                       |
| )COMMENT='This table will log errors for any operations'                                                                                                                                                  |
| ;                                                                                                                                                                                                         |
|                                                                                                                                                                                                           |
| create view "GMP_DEV"."PUBLIC"."FILE_AUDIT_HISTORY_CHECK" as select IN_DL_FLAG,INGESTED_FLAG,TARGET_FILE_SIZE_BYTES from "GMP_DEV"."PUBLIC"."FILE_AUDIT_HISTORY" where INGESTED_FLAG =1 and IN_DL_FLAG=0; |
|                                                                                                                                                                                                           |
| create or replace schema TESTSCHEMA;                                                                                                                                                                      |
|                                                                                                                                                                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 Row(s) produced. Time Elapsed: 0.520s
Goodbye!
